In [1]:
%load_ext line_profiler
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import jax.numpy as jnp
import jax
import symjax
import symjax.tensor as T
import copy
import time
import json
# RNTK_onediag_stripped
# RNTK_onediag_dual
from RNTK_onediag_dual import RNTK as RNTKOD_dual
from RNTK_onediag_dual import create_func as create_func_dual
from RNTK_onediag_stripped import RNTK as RNTKOD_stripped
from RNTK_onediag_stripped import create_func as create_func_stripped

In [3]:
# dataset = "trains"
# dataset = "bank"

In [4]:
# dic = {k:v for k,v in map(lambda x : x.split(), open("data" + "/" + dataset + "/" + dataset + ".txt", "r").readlines())}

In [5]:
def run_and_test(dic, type = "dual"):
    if not type == "dual":
        diag_func, rntk_dual = create_func_stripped(dic, True)
    else:
        diag_func, rntk_dual = create_func_dual(dic, True)
    fake_data_ti = np.zeros((dic["n_patrons1="],dic["n_entradasTi="]))
    fake_data_tiprime = np.zeros((dic["n_patrons1="],dic["n_entradasTiP="]))
    start = time.time()
    result = diag_func(fake_data_ti, fake_data_tiprime)
    # # gp_kernel = result[0]
    # # rntk_kernel = result[1]
    print("time to compute ", time.time() - start)
    return result, rntk_dual

In [6]:
dic = {}
dic["n_patrons1="] = 1#00 #// N (what affect symjax time)
dic["n_entradasTiP="] = 2 #99 works, 100 does not
dic["n_entradasTi="] = 2

In [7]:
result, rntk_dual = run_and_test(dic, "dual")
# result, rntk_dual = run_and_test(dic, "stripped")
result

time to create symjax 1.260556936264038
time to compute  1.812464952468872


array([[[ 5.7142606]],

       [[10.214497 ]]], dtype=float32)

lets execute the symjax

In [8]:
idxs = jnp.arange(0, sum(rntk_dual.dim_lengths) - rntk_dual.dim_num)
idxs

DeviceArray([0., 1., 2., 3.], dtype=float32)

In [9]:
ends = rntk_dual.ends_of_calced_diags
ends

array([0., 2., 3.])

In [10]:
np.equal(1, np.zeros(1))

array([False])

In [11]:
# fake_data_ti = np.zeros((dic["n_patrons1="],dic["n_entradasTi="]))
# fake_data_tiprime = np.zeros((dic["n_patrons1="],dic["n_entradasTiP="]))

In [12]:
# start = time.time()
# result = diag_func(fake_data_ti, fake_data_tiprime)
# # # gp_kernel = result[0]
# # # rntk_kernel = result[1]
# print(time.time() - start)
# result

In [13]:
# %%timeit
# diag_func(fake_data)